apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: jenkins
          image: jenkins/jenkins:2.541.1-jdk17
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000

          ports:
            - containerPort: 8080
            - containerPort: 50000

          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home