apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routex-hub-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
    targetRevision: master
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true