nameOverride: driver
fullnameOverride: routex-hub-driver-service
replicaCount: 2
image:
  repository: ghcr.io/goroutex/go-routex-driver-service
  tag: "v0.0.41" # sẽ được cập nhật theo tag/sha
  pullPolicy: IfNotPresent
containerPort: 8080
imagePullSecrets:
  - name: ghcr-secret
serviceAccount:
  create: true
  name: routex-hub-driver-sa
service:
  type: ClusterIP
  port: 80
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/routex"
  - name: SPRING_DATASOURCE_USERNAME
    value: routex
  - name: APP_REDIS_HOST
    value: redis
  - name: APP_REDIS_PORT
    value: "6379"
  - name: KAFKA_BOOTSTRAP_SERVER
    value: kafka:9092
envFromSecret:
  - name: SPRING_DATASOURCE_PASSWORD
    secretName: postgresql-secret
    key: POSTGRES_PASSWORD
  - name: JWT_SECRET
    secretName: jwt-secret
    key: JWT_SECRET
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: false
#  className: nginx
#  host: driver-dev.routex.local
#  path: /
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#  tls:
#    enabled: false
#    secretName: ""
