apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
  username: louispham091
  password: glpat-Ho9CdExdp9jpwcidQAzX2G86MQp1Omhpa3ZyCw.01.120qrjg7t